### PR TITLE
Convert is_front_defroster_on to bool

### PR DESCRIPTION
**Pull request by spkane**
At least for my M3 `is_front_defroster_on` seem to be be a boolean now, instead of an int.

### CODE REVIEW

**Comment by spkane** [comment]
@jsgoecke Is there any chance that we can get one of these fixes for the `is_front_defroster_on` setting merged?

**Comment by jsgoecke** [comment]
I believe this is already a bool.

**Comment by spkane** [comment]
@jsgoecke I'm confused by your comment. 

On master ( https://github.com/spkane/tesla/blob/master/states.go#L62 ) `is_front_defroster_on` is still an int, not a bool.

I have not tested this again since reporting it, but I'm unlcear why you said `I believe this is already a bool.` and just closed both places that this was reported. Are you saying that the fix was something else altogether?

**Comment by jsgoecke** [comment]
Because it is a Bool here:

https://github.com/jsgoecke/tesla/blob/master/states.go#L63

Am I misunderstanding the issue?

**Comment by spkane** [comment]
@jsgoecke Nope. You understand it. The github link in my response was to the wrong repo.

I see that it was fixed in 9 months ago in this commit: https://github.com/jsgoecke/tesla/commit/63274a8dbacbcd4400f1bf2da08664b4170a74b7

It just seemed like you were saying it wasn't a problem, versus it was already corrected. Got it. 

Thanks.

**Pull request closed without merging**
